version: '3.3'

services:
    centos-default: 
        build:
            context: ../../centos
        image: centos-default
    nginx:
        build:
            context: ../../nginx
            args:
               type: 'nodejs' 
        ports:
            - 80:80
        command: tail -f /dev/null
        depends_on:
            - centos-default
    nodejs:
        build: ../../nodejs
        volumes:
            - ./project:/usr/share/nginx/project
        command: tail -f /dev/null
        depends_on:
            - centos-default
        
